// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxnf4vdtmO-OM_rGqC4gm5LHOLTJXJhGw',
    appId: '1:179005405129:web:5a73d0125de4db3235da18',
    messagingSenderId: '179005405129',
    projectId: 'bodyscan-980a5',
    authDomain: 'bodyscan-980a5.firebaseapp.com',
    storageBucket: 'bodyscan-980a5.firebasestorage.app',
    measurementId: 'G-5E3S47MFC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgzGBXDFEF98dnNPgP_jh0vda6RugwYT8',
    appId: '1:179005405129:android:981f5b009c79b06135da18',
    messagingSenderId: '179005405129',
    projectId: 'bodyscan-980a5',
    storageBucket: 'bodyscan-980a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDod5TZkHj8gUg3MOHm6O0OTQ-n2dOfdaQ',
    appId: '1:179005405129:ios:3bef913ce313365a35da18',
    messagingSenderId: '179005405129',
    projectId: 'bodyscan-980a5',
    storageBucket: 'bodyscan-980a5.firebasestorage.app',
    iosBundleId: 'com.example.fitlyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDod5TZkHj8gUg3MOHm6O0OTQ-n2dOfdaQ',
    appId: '1:179005405129:ios:3bef913ce313365a35da18',
    messagingSenderId: '179005405129',
    projectId: 'bodyscan-980a5',
    storageBucket: 'bodyscan-980a5.firebasestorage.app',
    iosBundleId: 'com.example.fitlyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxnf4vdtmO-OM_rGqC4gm5LHOLTJXJhGw',
    appId: '1:179005405129:web:08aa373770f8d30e35da18',
    messagingSenderId: '179005405129',
    projectId: 'bodyscan-980a5',
    authDomain: 'bodyscan-980a5.firebaseapp.com',
    storageBucket: 'bodyscan-980a5.firebasestorage.app',
    measurementId: 'G-RPFVDGP51Q',
  );
}
